import 'package:hive_ce_flutter/hive_flutter.dart';

import '../models/app_enums.dart';
import '../models/resume.dart';
import '../models/resume_sections.dart';
import '../models/supporting_models.dart';
import '../models/user_settings.dart';
import '../constants/app_constants.dart';

/// HiveService — initializes Hive and opens all boxes.
/// Call HiveService.init() once in main() before runApp().
class HiveService {
  HiveService._();

  // ── Typed Box Accessors ───────────────────────────────────────────────────────

  static Box<Resume> get resumeBox => Hive.box<Resume>(AppConstants.resumeBox);

  static Box<SourceDocument> get sourceDocumentBox =>
      Hive.box<SourceDocument>(AppConstants.sourceDocumentBox);

  static Box<ResumeSection> get resumeSectionBox =>
      Hive.box<ResumeSection>(AppConstants.resumeSectionBox);

  static Box<CoverLetter> get coverLetterBox =>
      Hive.box<CoverLetter>(AppConstants.coverLetterBox);

  static Box<InterviewStudyGuide> get studyGuideBox =>
      Hive.box<InterviewStudyGuide>(AppConstants.interviewStudyGuideBox);

  static Box<UserSettings> get userSettingsBox =>
      Hive.box<UserSettings>(AppConstants.userSettingsBox);

  static Box<AddOnPurchase> get addOnPurchaseBox =>
      Hive.box<AddOnPurchase>(AppConstants.addOnPurchaseBox);

  // ── Init ─────────────────────────────────────────────────────────────────────

  /// Initializes Hive, registers all TypeAdapters, and opens all boxes.
  /// Must be called before runApp() and before any Hive box is accessed.
  static Future<void> init() async {
    await Hive.initFlutter();
    _registerAdapters();
    await _openBoxes();
    _ensureUserSettings();
  }

  static void _registerAdapters() {
    // Enum adapters (generated by hive_generator)
    if (!Hive.isAdapterRegistered(AppConstants.tierEnumTypeId)) {
      Hive.registerAdapter(TierEnumAdapter());
    }
    if (!Hive.isAdapterRegistered(AppConstants.fileTypeEnumTypeId)) {
      Hive.registerAdapter(FileTypeEnumAdapter());
    }
    if (!Hive.isAdapterRegistered(AppConstants.documentRoleEnumTypeId)) {
      Hive.registerAdapter(DocumentRoleEnumAdapter());
    }
    if (!Hive.isAdapterRegistered(AppConstants.extractionStatusEnumTypeId)) {
      Hive.registerAdapter(ExtractionStatusEnumAdapter());
    }
    if (!Hive.isAdapterRegistered(AppConstants.sectionTypeEnumTypeId)) {
      Hive.registerAdapter(SectionTypeEnumAdapter());
    }
    if (!Hive.isAdapterRegistered(AppConstants.skillCategoryEnumTypeId)) {
      Hive.registerAdapter(SkillCategoryEnumAdapter());
    }
    if (!Hive.isAdapterRegistered(AppConstants.questionCategoryEnumTypeId)) {
      Hive.registerAdapter(QuestionCategoryEnumAdapter());
    }
    if (!Hive.isAdapterRegistered(AppConstants.addOnTypeEnumTypeId)) {
      Hive.registerAdapter(AddOnTypeEnumAdapter());
    }
    if (!Hive.isAdapterRegistered(AppConstants.exportFormatEnumTypeId)) {
      Hive.registerAdapter(ExportFormatEnumAdapter());
    }
    if (!Hive.isAdapterRegistered(AppConstants.appThemeEnumTypeId)) {
      Hive.registerAdapter(AppThemeEnumAdapter());
    }

    // Model adapters (generated by hive_generator)
    if (!Hive.isAdapterRegistered(AppConstants.userSettingsTypeId)) {
      Hive.registerAdapter(UserSettingsAdapter());
    }
    if (!Hive.isAdapterRegistered(AppConstants.resumeTypeId)) {
      Hive.registerAdapter(ResumeAdapter());
    }
    if (!Hive.isAdapterRegistered(AppConstants.resumeSectionTypeId)) {
      Hive.registerAdapter(ResumeSectionAdapter());
    }
    if (!Hive.isAdapterRegistered(AppConstants.contactInfoTypeId)) {
      Hive.registerAdapter(ContactInfoAdapter());
    }
    if (!Hive.isAdapterRegistered(AppConstants.skillEntryTypeId)) {
      Hive.registerAdapter(SkillEntryAdapter());
    }
    if (!Hive.isAdapterRegistered(AppConstants.experienceEntryTypeId)) {
      Hive.registerAdapter(ExperienceEntryAdapter());
    }
    if (!Hive.isAdapterRegistered(AppConstants.educationEntryTypeId)) {
      Hive.registerAdapter(EducationEntryAdapter());
    }
    if (!Hive.isAdapterRegistered(AppConstants.certificationEntryTypeId)) {
      Hive.registerAdapter(CertificationEntryAdapter());
    }
    if (!Hive.isAdapterRegistered(AppConstants.sourceDocumentTypeId)) {
      Hive.registerAdapter(SourceDocumentAdapter());
    }
    if (!Hive.isAdapterRegistered(AppConstants.coverLetterTypeId)) {
      Hive.registerAdapter(CoverLetterAdapter());
    }
    if (!Hive.isAdapterRegistered(AppConstants.interviewStudyGuideTypeId)) {
      Hive.registerAdapter(InterviewStudyGuideAdapter());
    }
    if (!Hive.isAdapterRegistered(AppConstants.interviewQuestionTypeId)) {
      Hive.registerAdapter(InterviewQuestionAdapter());
    }
    if (!Hive.isAdapterRegistered(AppConstants.addOnPurchaseTypeId)) {
      Hive.registerAdapter(AddOnPurchaseAdapter());
    }
  }

  static Future<void> _openBoxes() async {
    await Future.wait([
      Hive.openBox<UserSettings>(AppConstants.userSettingsBox),
      Hive.openBox<Resume>(AppConstants.resumeBox),
      Hive.openBox<SourceDocument>(AppConstants.sourceDocumentBox),
      Hive.openBox<ResumeSection>(AppConstants.resumeSectionBox),
      Hive.openBox<CoverLetter>(AppConstants.coverLetterBox),
      Hive.openBox<InterviewStudyGuide>(AppConstants.interviewStudyGuideBox),
      Hive.openBox<AddOnPurchase>(AppConstants.addOnPurchaseBox),
    ]);
  }

  /// Ensures a UserSettings object exists on first launch.
  static void _ensureUserSettings() {
    final box = userSettingsBox;
    if (!box.containsKey(AppConstants.userSettingsKey)) {
      box.put(AppConstants.userSettingsKey, UserSettings.defaults());
    }
  }

  // ── UserSettings Convenience ─────────────────────────────────────────────────

  static UserSettings get settings =>
      userSettingsBox.get(AppConstants.userSettingsKey) ??
      UserSettings.defaults();

  static Future<void> saveSettings(UserSettings settings) async {
    await userSettingsBox.put(AppConstants.userSettingsKey, settings);
  }
}
